# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#trigger master branch
trigger:
 branches:
  include:
    - azure-pipelines-again


#use ubuntu image from pool agent
pool:
  vmImage: ubuntu-latest

steps:
- script:
      echo Hello, world!
      echo "this is my new file" > newfile.txt
      mkdir -p mydir
      mv newfile.txt mydir/
  displayName: "create new file and move into another dir"
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/$(dirname)'
    artifactName: 'MyArtifact'
