# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#trigger master branch
trigger:
 branches:
  include:
    - azure-pipelines-again


#use ubuntu image from pool agent
pool:
  vmImage: ubuntu-latest

steps:
- script: |
      echo "Hello World!" > myfile.txt
      echo "myfile.txt created."
      mkdir mydir
      mv myfile.txt mydir/
      echo "myfile.txt moved to mydir directory."

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/mydir'
    ArtifactName: 'my-artifact'